/**:
  ros__parameters:
    arena_x_length: 3.0
    arena_y_length: 3.0

    obstacles.x: [1.0]
    obstacles.y: [0.01]
    obstacles.r: 0.1

    # x0: -0.6
    # y0: 0.3
    # theta0: 1.28

    x0: 0.0
    y0: 0.0
    theta0: 0.0
